/*

 GAMEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\Tools\2948.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gamemapWidth 20
#define gamemapHeight 18
#define gamemapBank 0

extern unsigned const char gamemap[];

/* End of GAMEMAP.H */
