/*

 TITLESCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\Tools\2948.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define titleScreenWidth 20
#define titleScreenHeight 18
#define titleScreenBank 0

extern unsigned const char titleScreen[];

/* End of TITLESCREEN.H */
